# data:
data_dir: /cluster/scratch/aarslan/dlproject_datasets  # path to the unzipped dataset directories(H36m/AMASS/3DPW)
dataset: amass_3d # h36m_3d
body_model_dir: ../body_models/smpl_skeleton.npz
input_n: 15  # number of model's input frames
output_n: 45  # number of model's output frames.

# model:
model: mojo
nz: 16
rnn_type: gru
x_birnn: false
e_birnn: false
use_drnn_mlp: true
residual: true
nh_rnn: 256
nh_mlp: [300, 200]
posteriorbias: true
freqbasis: 'dct'
lambda_tf: 3
lambda_v: 0
beta: 1
robustkl: true

# run:
optimizer: adam
scheduler: lambda

seed: 42
n_epochs: 500  # number of epochs to train
batch_size: 64  # batch size
num_workers: 5  # 0 means use the same thread for preparing data
lr: 0.0001  # Learning rate of the optimizer ---- 0.0001 for h36m_3d
n_epoch_fix: 100
weight_decay: 0 # 0 for h36m_3d
use_scheduler: true
early_stop_patience: 10
clip_grad: 1.0  # select max norm to clip gradients
log_dir: ../logs/

# visualization:
visualize_from: test  # ['train','val','test']. Choose data split to visualize from(train-val-test).
n_viz: 2  # Numbers of sequences to visualize for each action
