# data:
body_model_dir: ../body_models/smpl_skeleton.npz
data_dir: /cluster/scratch/gsenthi/dlproject_datasets/  # path to the unzipped dataset directories(H36m/AMASS/3DPW)
dataset: amass_3d #h36m_3d #amass_3d
input_n: 10  # 2s of input
output_n: 25  # 0.4s of output
checkpoints_dir: ../logs/GRU_stsE_amass_10

# model:
model: rnn_stsE
recurrent_cell: gru # lstm or gru or rnn
input_hidden_size: 256
cell_size: 1024
output_hidden_size: 960  # 64 for with SPL, 960 for without
input_dim: 3  # dimensions of the input coordinates
st_gcnn_dropout: 0.1  # st-gcnn dropout

# run:
seed: 42
mode: test  # train or test or viz.
batch_size: 64
num_workers: 5

# visualization:
visualize_from: test  # train or val or test
n_viz: 2  # Numbers of sequences to visualize for each action
