exp_name: sts_amass_15

# data:
body_model_dir: ../body_models/smpl_skeleton.npz
data_dir: /cluster/scratch/gsenthi/dlproject_datasets/  # path to the unzipped dataset directories(H36m/AMASS/3DPW)
input_n: 15  # number of model's input frames
output_n: 45  # number of model's output frames
dataset: amass_3d #h36m_3d #amass_3d

# model:
model: stsgcn 
n_stgcnn_layers: 9  # number of stgcnn layers
n_ccnn_layers: 2  # number of layers for the Coordinate-Channel Convolution
n_tcnn_layers: 4  # number of layers for the Time-Extrapolator Convolution
ccnn_kernel_size: [1, 1]  # kernel for the C-CNN layers
tcnn_kernel_size: [3, 3]  # kernel for the Time-Extrapolator CNN layers
embedding_dim: 40  # dimensions for the coordinates of the embedding
input_dim: 3  # dimensions of the input coordinates
st_gcnn_dropout: 0.1  # st-gcnn dropout
ccnn_dropout: 0.0  # ccnn dropout
tcnn_dropout: 0.0  # tcnn dropout

# run:
mode: train  # choices=['train','test','viz']. Choose to train, test or visualize from the model. Either train, test or viz.
optimizer: adam
scheduler: multi_step_lr
seed: 42
n_epochs: 50  # number of epochs to train
batch_size: 256  # batch size
num_workers: 5  # 0 means use the same thread for preparing data
lr: 0.01  # Learning rate of the optimizer
weight_decay: 0.00001
use_scheduler: True  # use MultiStepLR scheduler
early_stop_patience: 5
milestones: [15, 25, 35, 40]  # the epochs after which the learning rate is adjusted by gamma
gamma: 0.1  # gamma correction to the learning rate, after reaching the milestone epochs
clip_grad: null  # select max norm to clip gradients
log_dir: ../logs/

# visualization:
visualize_from: test  # ['train','val','test']. Choose data split to visualize from(train-val-test).
n_viz: 2  # Numbers of sequences to visualize for each action
